### ISSUE TITLE
the settings lost in 3.4.x

### ISSUE THREAD

**Issue by aozhi2nd** [edosoft/redmine-inherit-fields-plugin#24] opened 2018-01-19 03:48 UTC
in redmine 3.4.x , 
select a few fields to inherit 
click apply ,but the settings lost

**Comment by 0l3er** [comment] 2018-05-07 23:13
Same problem

**Comment by levneploh** [comment] 2018-10-08 09:02
same with 3.4.6.stable

**Comment by realMaxA** [comment] 2018-10-23 06:38
+1

**Comment by ramlez** [comment] 2018-11-19 21:15
+1

**Comment by vphantom** [comment] 2019-01-21 19:50
Note: this seems to be a duplicate of #19, which contains a possible fix.

**Comment by michaelliu1213** [comment] 2019-04-03 17:57
> in redmine 3.4.x ,
> select a few fields to inherit
> click apply ,but the settings lost

try this fork, it's worked in in redmine 3.4.2 
```
git clone https://github.com/dkd/redmine-inherit-fields-plugin redmine_subtasks_inherited_fields
```

**Comment by davidverdu** [comment] 2019-05-15 09:50
This isssue has been solved thanks to a contribution

**Closed by davidverdu** 2019-05-15 09:50 UTC
Labels: bug
